projectName: "vulnerable-API"
sourcePath: ""

name: Polaris Vulnerability Scan
on:
push:
### run scans on each push to branches
branches: [ main, master ]
schedule:
### run scheduled scans to ensure repositories are scanned even if not
actively developed
- cron: '55 16 * * *'
workflow_dispatch:
### allow manual trigger if needed
jobs:
build:
### RUN via METRO-NETWORK (VPN)
runs-on:
- self-hosted
- Linux
- metro-network
env:
PROJECT_NAME: ${{github.event.repository.name }}
steps:
- name: Checkout Source
uses: actions/checkout@v4
- name: Set up JDK 21
uses: actions/setup-java@v4
with:
java-version: '21'
distribution: 'temurin'
- name: Polaris Scan
uses: synopsys-sig/synopsys-action@v1.9.0
with:
### SCANNING: Required fields
polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
polaris_assessment_types: "SCA,SAST"
### SCANNING: Optional fields
polaris_application_name: M.SAM ##!!! <your solution name>
polaris_project_name: ${{ env.PROJECT_NAME }}